[plugins] Fix build \w clang 16
Clang 16 has made -Wincompatible-function-pointer-types and other
warnigns enabled by default. Hence we're getting erros such as:

msd-a11y-keyboard-atspi.c:131:53: error: incompatible function pointer types passing
      'gboolean (const AtspiDeviceEvent *, void *)' (aka 'int (const struct _AtspiDeviceEvent *, void *)') to
      parameter of type 'AtspiDeviceListenerCB' (aka 'int (*)(struct _AtspiDeviceEvent *, void *)')
      [-Wincompatible-function-pointer-types]
        self->listener = atspi_device_listener_new (on_key_press_event,
                                                    ^~~~~~~~~~~~~~~~~~

Bug: https://bugs.gentoo.org/881315
Co-authored-by: David Carlos Manuelda <StormByte@gmail.com>
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>